//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class administrador
    {
        public administrador()
        {
            this.transaccions = new HashSet<transaccion>();
            this.apuestas = new HashSet<apuesta>();
        }
    
        public int id_administrador { get; set; }
        public string nombre { get; set; }
        public sbyte estado { get; set; }
        public string tipo { get; set; }
        public string correo_electronico { get; set; }
    
        public virtual ICollection<transaccion> transaccions { get; set; }
        public virtual ICollection<apuesta> apuestas { get; set; }
    }
}
