//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente
    {
        public cliente()
        {
            this.transaccions = new HashSet<transaccion>();
            this.oferta_apuesta = new HashSet<oferta_apuesta>();
        }
    
        public int id_cliente { get; set; }
        public double monto_actual { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public sbyte estado { get; set; }
        public string correo_electronico { get; set; }
    
        public virtual ICollection<transaccion> transaccions { get; set; }
        public virtual ICollection<oferta_apuesta> oferta_apuesta { get; set; }
    }
}
