//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class oferta_apuesta
    {
        public int id_cliente { get; set; }
        public int id_apuesta { get; set; }
        public int id_administrador { get; set; }
        public string terminos_apuesta { get; set; }
        public System.DateTime fecha_creacion_apuesta { get; set; }
        public System.DateTime duracion_apuesta { get; set; }
        public double monto_apostado { get; set; }
        public System.DateTime fecha_oferta { get; set; }
        public sbyte condicion_a_cumplirse { get; set; }
    
        public virtual apuesta apuesta { get; set; }
        public virtual cliente cliente { get; set; }
    }
}
